--- #YAML:1.0
name: Posy-Plugin-Dump
version: 0.47
author:
  - Kathryn Andersen
abstract: |-
  Posy plugin to aid debugging by dumping object contents.
license: perl
requires:
  Data::Dumper: 2.121
  Posy: 0.95
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::Dump:
    file: lib/Posy/Plugin/Dump.pm
    version: 0.47
generated_by: Module::Build version 0.261
